version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    network_mode: "host"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:root123@localhost:5432/abuse_moderation